# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macOS-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    # Fetch the public IP address of the macOS VM and print it to the console
    ip=$(curl -s https://api.ipify.org)
    echo "macOS VM IP address: $ip"
  displayName: 'Get macOS VM IP'

- script: |
    echo "Agent IP Address: $AGENT_IP_ADDRESS"
    echo "Agent OS: $AGENT_OS"
  displayName: 'Print Diagnostic Information'
  
- script: |
    IP=($(curl -s http://ipinfo.io/json | jq '.ip' | sed -e 's/^"//' -e 's/"$//'))
    echo "This Microsoft hosted agent public IP is: $IP"
  displayName: 'Get Agent Public IP'
  
- script: |
    # Authenticate with Azure
    az login --service-principal -u <service_principal_id> -p <service_principal_password> --tenant <tenant_id>

    # Create a resource group
    az group create --name myResourceGroup --location eastus

    # Create a VM
    az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --admin-username azureuser --admin-password P@ssw0rd1234

    # Retrieve the username and password
    username=$(az vm show -g myResourceGroup -n myVM --query 'osProfile.adminUsername' -o tsv)
    password=$(az vm show -g myResourceGroup -n myVM --query 'osProfile.adminPassword' -o tsv)

    echo "Username: $username"
    echo "Password: $password"
  displayName: 'Create and Retrieve VM Credentials'

