# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      #running license validator console
      $result = & "D:\Test\LicenseKeyValidatorConsole\LicenseKeyValidatorConsole\LicenseKeyValidatorConsole\bin\Debug\LicenseKeyValidatorConsole.exe" /platform:WPF /version:25.1.35 /licensekey:MDAxQDMyMzUyZTMwMmUzMEhrMGovQVhCd3Q0cHpPaEs5Tk1LekdvVlZSVGcxdS9EM3MzdWVOSFR3dU
      # Check the output of the tool
      if ($result.Trim() -eq "Valid Key") {
        Write-Output "License key is valid. Proceeding to FinalBuilder task."
      }
      else {
        Write-Host "Invalid license key. Terminating the pipeline."
        exit 1  # Terminate the pipeline with a non-zero exit code
      }
  displayName: 'Validating License Key'

- task: FinalBuilder@1
  inputs:
    projectfile: 'D:\Test\LicenseKeyValidatorConsole\FinalBuilder\Test.fbp8'
