# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: D:\LicenseKeyValidatorConsole\LicenseValidateScript.ps1

  displayName: 'Validating License Key'
  

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $result = "D:\LicenseKeyValidatorConsole\LicenseKeyValidatorConsole.exe" /platform:Blazor /version:25.1.34 /licensekey:${env:SYNCFUSION_LICENSE}
      Write-Host $result
  
  displayName: Validation Test


- task: FinalBuilder@1
  inputs:
    projectfile: 'D:\Test\LicenseKeyValidatorConsole\FinalBuilder\Test.fbp8'
